/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ptts.dashboard;

import ptts.fun.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author vihas
 */
public class Menu1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
       ui.setNorthPane(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainticket = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bus = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LocalTrain = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Metro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        metroticket = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        busticket = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1880, 870));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trainticket.setBackground(new java.awt.Color(255, 255, 255));
        trainticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainticketMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/ticket.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Local Train");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Train Ticket");

        javax.swing.GroupLayout trainticketLayout = new javax.swing.GroupLayout(trainticket);
        trainticket.setLayout(trainticketLayout);
        trainticketLayout.setHorizontalGroup(
            trainticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainticketLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trainticketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(trainticketLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trainticketLayout.setVerticalGroup(
            trainticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainticketLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(trainticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 270, 280));

        Bus.setBackground(new java.awt.Color(255, 255, 255));
        Bus.setPreferredSize(new java.awt.Dimension(288, 301));
        Bus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/bus (4).png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUS");

        javax.swing.GroupLayout BusLayout = new javax.swing.GroupLayout(Bus);
        Bus.setLayout(BusLayout);
        BusLayout.setHorizontalGroup(
            BusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        BusLayout.setVerticalGroup(
            BusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        getContentPane().add(Bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 280, 290));

        LocalTrain.setBackground(new java.awt.Color(255, 255, 255));
        LocalTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocalTrainMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/train (1).png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("LOCAL TRAIN");

        javax.swing.GroupLayout LocalTrainLayout = new javax.swing.GroupLayout(LocalTrain);
        LocalTrain.setLayout(LocalTrainLayout);
        LocalTrainLayout.setHorizontalGroup(
            LocalTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalTrainLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LocalTrainLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        LocalTrainLayout.setVerticalGroup(
            LocalTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocalTrainLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(LocalTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 270, 290));

        Metro.setBackground(new java.awt.Color(255, 255, 255));
        Metro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetroMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("METRO");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/metro.png"))); // NOI18N

        javax.swing.GroupLayout MetroLayout = new javax.swing.GroupLayout(Metro);
        Metro.setLayout(MetroLayout);
        MetroLayout.setHorizontalGroup(
            MetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MetroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(MetroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MetroLayout.setVerticalGroup(
            MetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MetroLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Metro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 290, 290));

        metroticket.setBackground(new java.awt.Color(255, 255, 255));
        metroticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metroticketMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/metrotick.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Metro Ticket");

        javax.swing.GroupLayout metroticketLayout = new javax.swing.GroupLayout(metroticket);
        metroticket.setLayout(metroticketLayout);
        metroticketLayout.setHorizontalGroup(
            metroticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(metroticketLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        metroticketLayout.setVerticalGroup(
            metroticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metroticketLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );

        getContentPane().add(metroticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 280, 280));

        busticket.setBackground(new java.awt.Color(255, 255, 255));
        busticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busticketMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/ticket (2).png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Bus Ticket");

        javax.swing.GroupLayout busticketLayout = new javax.swing.GroupLayout(busticket);
        busticket.setLayout(busticketLayout);
        busticketLayout.setHorizontalGroup(
            busticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(busticketLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        busticketLayout.setVerticalGroup(
            busticketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busticketLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(24, 24, 24))
        );

        getContentPane().add(busticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 280, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocalTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocalTrainMouseClicked
       Train t = new Train();
       t.setVisible(true);
       t.setLocationRelativeTo(null);
       Dashboard dash = new Dashboard();  
        dash.dispose(); 
    }//GEN-LAST:event_LocalTrainMouseClicked

    private void BusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusMouseClicked
       Bus bus = new Bus();
       bus.setVisible(true);
       bus.setLocationRelativeTo(null);
       Dashboard dash = new Dashboard();  
        dash.dispose(); 
    }//GEN-LAST:event_BusMouseClicked

    private void MetroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MetroMouseClicked

    private void trainticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainticketMouseClicked
        Dashboard dash = new Dashboard();  
       dash.toBack();
       LOCAL l = new LOCAL();
       l.setVisible(true);
       l.toFront();
    }//GEN-LAST:event_trainticketMouseClicked

    private void busticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busticketMouseClicked
        Dashboard dash = new Dashboard();  
        //dash.dispose(); 
        dash.toBack();
        BusTicket bt = new BusTicket();
       bt.setVisible(true);
       bt.toFront();
    }//GEN-LAST:event_busticketMouseClicked

    private void metroticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metroticketMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_metroticketMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bus;
    private javax.swing.JPanel LocalTrain;
    private javax.swing.JPanel Metro;
    private javax.swing.JPanel busticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel metroticket;
    private javax.swing.JPanel trainticket;
    // End of variables declaration//GEN-END:variables
}
