/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ptts.fun;
import ptts.fun.QRT3;
import ptts.fun.QRT1;
import ptts.fun.QRT7;
import ptts.fun.QRT4;
import ptts.fun.QRT2;
import ptts.fun.QRT9;
import ptts.fun.QRT6;
import ptts.fun.QRT5;
import ptts.fun.LOCAL;
import ptts.fun.QRT8;
import ptts.dashboard.Dashboard;

/**
 *
 * @author HARSHIT KADAM
 */
public class LOCAL extends javax.swing.JFrame {

    /**
     * Creates new form LOCAL
     */
    public LOCAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jcmb_Origin = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Jcmb_Destination = new javax.swing.JComboBox<>();
        btnProceed = new javax.swing.JButton();
        nmmtpan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HARBOUR LINE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("SELECT ORIGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 207, 177, 40));

        Jcmb_Origin.setBackground(new java.awt.Color(51, 153, 255));
        Jcmb_Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------------", "PANVEL ", "KHANDESHWAR", "MANSAROVAR", "KHARGHAR", "BELAPUR C.B.D", "SEASWOODS DARAVAE", "NERUL", "JUINAGAR", "SANPADA", "VASHI" }));
        Jcmb_Origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcmb_OriginActionPerformed(evt);
            }
        });
        jPanel1.add(Jcmb_Origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 207, 297, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("SELECT DESTINATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 320, -1, 40));

        Jcmb_Destination.setBackground(new java.awt.Color(51, 153, 255));
        Jcmb_Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------------", "PANVEL ", "KHANDESHWAR", "MANSAROVAR", "KHARGHAR", "BELAPUR C.B.D", "SEASWOODS DARAVAE", "NERUL", "JUINAGAR", "SANPADA", "VASHI" }));
        Jcmb_Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcmb_DestinationActionPerformed(evt);
            }
        });
        jPanel1.add(Jcmb_Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 320, 297, 40));

        btnProceed.setBackground(new java.awt.Color(51, 153, 255));
        btnProceed.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProceed.setText("PROCEED");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });
        jPanel1.add(btnProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 449, 142, 48));

        nmmtpan.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout nmmtpanLayout = new javax.swing.GroupLayout(nmmtpan);
        nmmtpan.setLayout(nmmtpanLayout);
        nmmtpanLayout.setHorizontalGroup(
            nmmtpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        nmmtpanLayout.setVerticalGroup(
            nmmtpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(nmmtpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1550, 760));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ptts/image/back.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(back)
                .addContainerGap(1488, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(back)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jcmb_OriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcmb_OriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcmb_OriginActionPerformed

    private void Jcmb_DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcmb_DestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcmb_DestinationActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==2) //for Khandeshwar
        {
            {
              QRT1 qr = new QRT1();
                qr.setVisible(true);
                this.setVisible(false);  
            }
        }
        else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==3)  //for Mansorovar
            {
              QRT2 qr = new QRT2();
                qr.setVisible(true);
                this.setVisible(false);  
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==4)  //for Khanrghar
            {
              QRT3 qr = new QRT3();
                qr.setVisible(true);
                this.setVisible(false);  
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==5) //for Belapur C.B.D
            {
              QRT4 qr = new QRT4();
                qr.setVisible(true);
                this.setVisible(false);  
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==6) //for Seawoods Darave
            {
              QRT5 qr = new QRT5();
                qr.setVisible(true);
                this.setVisible(false);  
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==7)   //For Nerul
            {
              QRT6 qr = new QRT6();
                qr.setVisible(true);
                this.setVisible(false);  
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==8)   //for Juinagar
            {
              QRT7 qr = new QRT7();
                qr.setVisible(true);
                this.setVisible(false);
            }
          else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==9) // for sanapda
            {
              QRT8 qr = new QRT8();
                qr.setVisible(true);
                this.setVisible(false);        
            }
         else 
            if(Jcmb_Origin.getSelectedIndex()==1 && Jcmb_Destination.getSelectedIndex()==10)   //for vashi
            {
              QRT9 qr = new QRT9();
                qr.setVisible(true);
                this.setVisible(false); 
            }
        
        
        
    }//GEN-LAST:event_btnProceedActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.toBack();
        Dashboard d = new Dashboard();
        d.setVisible(true);
        d.toFront();

    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOCAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOCAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOCAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOCAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOCAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jcmb_Destination;
    private javax.swing.JComboBox<String> Jcmb_Origin;
    private javax.swing.JLabel back;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nmmtpan;
    // End of variables declaration//GEN-END:variables
}
